export const formJuridiques = [
  'SARL',
  'SARL AU',
  'AE',
  'Coopérative',
  'SNC',
  'Personne physique',
]

export const regions = ['Oriental', 'TTH']

export const communes = {
  oriental: [
    'Oujda',
    'Berkane',
    'Nador',
    'Jerada',
    'Taourirt',
    'Driouch',
    'Guercif',
    'Figuig',
  ],
  tth: ['Al Hoceima', 'Tanger Tetouan'],
}

export const provinces = {
  oujda: [
    'Oujda-Angad',
    'Bni Drar',
    'Naima',
    'Ain Sfa',
    'Bni Khaled',
    'Bsara',
    'Isly',
    'Mestferki',
    'Sidi Boulenouar',
    'Sidi Moussa Lemhaya',
  ],
  berkane: [
    'Berkane',
    'Ahfir',
    'Ain Erreggada',
    'Aklim',
    'Saidia',
    'Sidi Slimane Echcharaa',
    'Aghbal',
    'Boughriba',
    'Chouihia',
    'Fezouane',
    'Laatamna',
    'Madagh',
    'Rislane',
    'Sidi Bouhria',
    'Tafoughalt',
    'Zegzel',
  ],
  driouch: [
    'Driouch',
    'Ain Zohra',
    'Ain Mait',
    'Amejjaou',
    'Azlaf',
    'Bentaieb',
    'Bni Marghnine',
    'Boudinar',
    'Dar El Kebdani',
    'Iferni',
    'Ijermaouas',
    'Mahjer',
    'Midar',
    'Ouardana',
    'Oulad Amghar',
    'Oulad Boubker',
    'Tafersit',
    'Talilit',
    'Tazaghine',
    'Temsamane',
    'Trougout',
    'Tsaft',
  ],
  figuig: [
    'Figuig',
    'Bouarfa',
    'Abbou Lakhal',
    'Ain Chouater',
    'Bni Guil',
    'Bni Tadjite',
    'Bouanane',
    'Bouchaouene',
    'Maatarka',
    'Talsint',
    'Tendrara',
    'Ain Chir',
  ],
  jerada: [
    'Jerada',
    'Ain Bni Mathar',
    'Touissit',
    'Gafait',
    'Guenfouda',
    'Laaouinate',
    'Lebkhata',
    'Mrija',
    'Oulad Ghziyel',
    'Oulad Sidi Abdelhakem',
    'Ras Asfour',
    'Sidi Boubker',
    'Tiouli',
  ],
  nador: [
    'Nador',
    'Al Aaroui',
    'Bni Ansar',
    'Zaio',
    'Zeghanghane',
    'Afsou',
    'Al Barkanyene',
    'Arekmane',
    'Bni Bouifrour',
    'Bni Chiker',
    'Bni Oukil Oulad Mhand',
    'Bni Sidel Louta',
    'Bouarg',
    'Farkhana',
    'Hassi Berkane',
    'Iaazzanene',
    'Ihaddadene',
    'Iksane',
    'Oulad Daoud Zkhanine',
    'Ouled Settout',
    'Ras El Ma',
    'Selouane',
    'Tiztoutine',
    'Mtalssa',
  ],
  taourirt: [
    'Taourirt',
    'Debdou',
    'El Aioun Sidi Mellouk',
    'Ahl Oued Za',
    'Ain Lehjer',
    'El Atef',
    'Gteter',
    'Mecharaa Hammadi',
    'Melg El Ouidane',
    'Mestergmer',
    'Oulad Mhamed',
    'Sidi Ali Belkhassem',
    'Sidi Lahsen',
    'Tancherfi',
  ],
  guercif: ['Guercif', 'Tendrara', 'Ain Erreggada'],
  // TTH
  tangertetouan: [
    'Tanger',
    'Tetouan',
    'Taounate',
    'Ouel Laou',
    'Mdiq-Fnideq',
    'Azla',
    'Zaouiat Sidi Kacem',
    'Al Hamra',
    'Beni Harchen',
    'Jbel Lahbib',
    'Belounech',
    'Bni leit',
    'Dar Bni Karrich',
    'Mallalienne',
    'Al Oued',
    'Saddina',
    'Bghaghza',
    'Sahtyine',
    'Martil',
    'Allyene',
    'Bni Said',
    'Ain Lahsan',
    'Souk Kdim',
    'Zaitoune',
    'Zinat',
    'Al Kharroub',
    'Sahtryine',
    'Chefchaouen',
    'Ouezzane',
    'Fahs-Bni Makada',
    'Bni Darkoul',
    'Bab Taza',
  ],
  alhoceima: [
    'Al Hoceima',
    'Sidi Boutmim',
    'Bni Bouayach',
    'Imzouren',
    'Bni Bouayach',
    'Imzouren',
    'Abdelghaya Souahel',
    'Ait Youssef Ou Ali',
    'Tamorot',
    'Nekkour',
    'Bni Boufrah',
    'Bni Gmil',
    'Bni Ammart',
    'Imrabten',
    'Targuist',
    'Ketama',
  ],
}

export const experiences = [
  "Moins d'un an",
  'de 1 à 3 ans',
  'de 3 à 5 ans',
  'plus de 5 ans',
]

export const secteursGlobal = [
  'Agriculture',
  'Artisanat',
  'pêche',
  'Commerce',
  'Tourisme CHR',
  'Transport',
  'Service',
  'Education',
  'Autres',
]

export const secteurs = {
  agriculture: [
    'apiculture',
    'aviculuture',
    'oléoculture',
    'Cuniculture',
    'Amandier',
    'Champignons',
    "Elevage d'ovins",
    'Elevage de bovins',
    'Elevage de caprins',
    'Figuier de Barbarie',
    'Figuier',
    'Héliciculture',
    'Lait',
    'Fromagerie artisanale',
    'Oléiculture',
    'Plantes aromatique et médicinales ',
    'Pépinière',
    'elevage des poulets',
    'Autre - Agriculture',
  ],
  artisanat: [
    'menuiserie alu',
    'Vannerie',
    'Couture',
    'Electricité et plomberie de Bâtiment',
    'Ferronnerie',
    'Maroquinerie',
    'Menuiserie Bois',
    'Peinture Bâtiment',
    'Construction bâtiment',
    'Platrier',
    'Tapisserie',
    'Tissage et broderie',
    'Tapis',
    'Boulangerie/petite restauration',
    'Fabrication de savon artisanale',
    'Coiffure et esthétique',
    'marbre',
    'menuiserie aluminium',
    'inox',
    'menuiserie',
    'menuiserie métallique',
    'Autre - Artisanat',
  ],
  pêche: [
    'peche artisanale',
    'peche moderne',
    'Aquaculture',
    'Conditionnement et transformation des produits de la mer',
    'Autre - Pêche',
  ],
  commerce: ['Commerce de détails', 'Commerce de gros', 'Autre - Commerce'],
  tourismechr: [
    'Café',
    'Hôtellerie',
    'Restauration',
    'Traiteur',
    'Parc de loisirs',
    'Agence de voyage',
    'CHR',
    'Tourisme',
    'Boulangerie pâtisserie',
    'Autre - Tourisme-CHR',
  ],
  transport: [
    'Transport de marchandises',
    'Transport de voyageurs',
    'Autre - Transport',
  ],
  service: [
    "Organisation d'événements",
    'Agence de location de voiture',
    'Nettoyage',
    'Jardinage',
    'Gardiennage',
    'Imprimerie',
    'Agence de communication',
    'Cabinet de formation',
    'Livraison',
    'Reparation matériel élctrique et électronique',
    'Mécanique et électricité automobile',
    'peinture bâtiments',
    'agence multi-services',
    'marketing digital',
    'photographie',
    'design intérieur et extérieur',
    'plateforme digitale',
    'plateforme digitale',
    'plomberie et dépannage électrique',
    'installation électrique',
    'installation électrique et industrielle',
    'cabinet médical',
    'Autre - Service',
  ],
  education: [
    'Soutien scolaire',
    'Garderie et crèche',
    "Ecoles d'enseignement général privés",
    'Etablissements de formation professionnelle',
    'etablissement préscolaire',
    'Autre - Education',
  ],
  autres: [
    'travaux divers',
    'btp',
    'industrie',
    'audio visuel',
    'industrie légère',
    'divertissement',
    'production et commercialisation des produits du terroir',
    'recyclage',
    'sport et divertissement',
    'industrie agroalimentaire',
    'Autre - Autres',
  ],
}
