export const formJuridiques = [
  'SARL',
  'SARL AU',
  'AE',
  'Coopérative',
  'SNC',
  'Personne physique',
]

export const regions = ['Oriental', 'TTH']

export const communes = {
  oriental: [
    'Oujda',
    'Berkane',
    'Nador',
    'Jerada',
    'Taourirt',
    'Driouch',
    'Guercif',
    'Figuig',
  ],
  tth: ['Al Hoceima', 'Tanger Tetouan'],
}

export const provinces = {
  oujda: [
    'Oujda-Angad',
    'Bni Drar',
    'Naima',
    'Ain Sfa',
    'Bni Khaled',
    'Bsara',
    'Isly',
    'Mestferki',
    'Sidi Boulenouar',
    'Sidi Moussa Lemhaya',
  ],
  berkane: [
    'Berkane',
    'Ahfir',
    'Ain Erreggada',
    'Aklim',
    'Saidia',
    'Sidi Slimane Echcharaa',
    'Aghbal',
    'Boughriba',
    'Chouihia',
    'Fezouane',
    'Laatamna',
    'Madagh',
    'Rislane',
    'Sidi Bouhria',
    'Tafoughalt',
    'Zegzel',
  ],
  driouch: [
    'Driouch',
    'Ain Zohra',
    'Ain Mait',
    'Amejjaou',
    'Azlaf',
    'Bentaieb',
    'Bni Marghnine',
    'Boudinar',
    'Dar El Kebdani',
    'Iferni',
    'Ijermaouas',
    'Mahjer',
    'Midar',
    'Ouardana',
    'Oulad Amghar',
    'Oulad Boubker',
    'Tafersit',
    'Talilit',
    'Tazaghine',
    'Temsamane',
    'Trougout',
    'Tsaft',
  ],
  figuig: [
    'Figuig',
    'Bouarfa',
    'Abbou Lakhal',
    'Ain Chouater',
    'Bni Guil',
    'Bni Tadjite',
    'Bouanane',
    'Bouchaouene',
    'Maatarka',
    'Talsint',
    'Tendrara',
    'Ain Chir',
  ],
  jerada: [
    'Jerada',
    'Ain Bni Mathar',
    'Touissit',
    'Gafait',
    'Guenfouda',
    'Laaouinate',
    'Lebkhata',
    'Mrija',
    'Oulad Ghziyel',
    'Oulad Sidi Abdelhakem',
    'Ras Asfour',
    'Sidi Boubker',
    'Tiouli',
  ],
  nador: [
    'Nador',
    'Al Aaroui',
    'Bni Ansar',
    'Zaio',
    'Zeghanghane',
    'Afsou',
    'Al Barkanyene',
    'Arekmane',
    'Bni Bouifrour',
    'Bni Chiker',
    'Bni Oukil Oulad Mhand',
    'Bni Sidel Louta',
    'Bouarg',
    'Farkhana',
    'Hassi Berkane',
    'Iaazzanene',
    'Ihaddadene',
    'Iksane',
    'Oulad Daoud Zkhanine',
    'Ouled Settout',
    'Ras El Ma',
    'Selouane',
    'Tiztoutine',
    'Mtalssa',
  ],
  taourirt: [
    'Taourirt',
    'Debdou',
    'El Aioun Sidi Mellouk',
    'Ahl Oued Za',
    'Ain Lehjer',
    'El Atef',
    'Gteter',
    'Mecharaa Hammadi',
    'Melg El Ouidane',
    'Mestergmer',
    'Oulad Mhamed',
    'Sidi Ali Belkhassem',
    'Sidi Lahsen',
    'Tancherfi',
  ],
  guercif: ['Guercif', 'Tendrara', 'Ain Erreggada'],
  // TTH
  tangertetouan: [
    'Tanger',
    'Tetouan',
    'Taounate',
    'Ouel Laou',
    'Mdiq-Fnideq',
    'Azla',
    'Zaouiat Sidi Kacem',
    'Al Hamra',
    'Beni Harchen',
    'Jbel Lahbib',
    'Belounech',
    'Bni leit',
    'Dar Bni Karrich',
    'Mallalienne',
    'Al Oued',
    'Saddina',
    'Bghaghza',
    'Sahtyine',
    'Martil',
    'Allyene',
    'Bni Said',
    'Ain Lahsan',
    'Souk Kdim',
    'Zaitoune',
    'Zinat',
    'Al Kharroub',
    'Sahtryine',
    'Chefchaouen',
    'Ouezzane',
    'Fahs-Bni Makada',
    'Bni Darkoul',
    'Bab Taza',
  ],
  alhoceima: [
    'Al Hoceima',
    'Sidi Boutmim',
    'Bni Bouayach',
    'Imzouren',
    'Bni Bouayach',
    'Imzouren',
    'Abdelghaya Souahel',
    'Ait Youssef Ou Ali',
    'Tamorot',
    'Nekkour',
    'Bni Boufrah',
    'Bni Gmil',
    'Bni Ammart',
    'Imrabten',
    'Targuist',
    'Ketama',
  ],
}

export const experiences = [
  "Moins d'un an",
  'de 1 à 3 ans',
  'de 3 à 5 ans',
  'plus de 5 ans',
]

export const secteursGlobal = [
  'Agriculture',
  'Artisanat',
  'pêche',
  'Commerce',
  'Tourisme CHR',
  'Transport',
  'Service',
  'Education',
  'Autres',
]

type Secteurs = {
  [key: string]: string[]
}

export const secteurs: Secteurs = {
  agriculture: [
    'Amandier',
    'Apiculture',
    'Aviculuture',
    'Champignons',
    'Cuniculture',
    "Elevage d'ovins",
    'Elevage de bovins',
    'Elevage de caprins',
    'Figuier',
    'Figuier de Barbarie',
    'Fromagerie artisanale',
    'Héliciculture',
    'Lait',
    'Oléiculture',
    'Oléoculture',
    'Plantes aromatiques et médicinales',
    'Pépinière',
    'Elevage des poulets',
    'Autre - Agriculture',
  ],
  artisanat: [
    'Boulangerie/petite restauration',
    'Construction bâtiment',
    'Coiffure et esthétique',
    'Couture',
    'Electricité et plomberie de Bâtiment',
    'Fabrication de savon artisanale',
    'Ferronnerie',
    'Inox',
    'Marbre',
    'Menuiserie',
    'Menuiserie aluminium',
    'Menuiserie Bois',
    'Peinture Bâtiment',
    'Plâtrier',
    'Tapis',
    'Tapisserie',
    'Tissage et broderie',
    'Vannerie',
    'Autre - Artisanat',
  ],
  pêche: [
    'Aquaculture',
    'Conditionnement et transformation des produits de la mer',
    'Pêche artisanale',
    'Pêche moderne',
    'Autre - Pêche',
  ],
  commerce: ['Commerce de détails', 'Commerce de gros', 'Autre - Commerce'],
  tourismechr: [
    'Agence de voyage',
    'Boulangerie pâtisserie',
    'Café',
    'CHR',
    'Hôtellerie',
    'Parc de loisirs',
    'Restauration',
    'Tourisme',
    'Traiteur',
    'Autre - Tourisme-CHR',
  ],
  transport: [
    'Transport de marchandises',
    'Transport de voyageurs',
    'Autre - Transport',
  ],
  service: [
    'Agence de communication',
    'Agence de location de voiture',
    'Cabinet de formation',
    'Design intérieur et extérieur',
    'Gardiennage',
    'Imprimerie',
    'Installation électrique',
    'Installation électrique et industrielle',
    'Jardinage',
    'Livraison',
    'Mécanique et électricité automobile',
    'Marketing digital',
    'Nettoyage',
    'Photographie',
    'Peinture bâtiments',
    'Plateforme digitale',
    'Reparation matériel électrique et électronique',
    'Plomberie et dépannage électrique',
    'Autre - Service',
  ],
  education: [
    "Ecoles d'enseignement général privés",
    'Etablissements de formation professionnelle',
    'Etablissement préscolaire',
    'Garderie et crèche',
    'Soutien scolaire',
    'Autre - Education',
  ],
  autres: [
    'Audio visuel',
    'BTP',
    'Divertissement',
    'Industrie',
    'Industrie agroalimentaire',
    'Industrie légère',
    'Production et commercialisation des produits du terroir',
    'Recyclage',
    'Sport et divertissement',
    'Travaux divers',
    'Autre - Autres',
  ],
}
